name: auto tag workflow

on:
 workflow_dispatch:

jobs:
  create_tag:
    name: create_tag
    uses: atulec016/central_call/.github/workflows/tag_new.yml@main
    secrets:
      GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
