name: Upload Files to S3

on:
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: list command
      run: |
        ls -alt ${{ github.workspace }}
        cat ${{ github.workspace }}/test/atul.txt

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
