name: test_yaml

on: 
  create:
    tags: 
      - '*'
  workflow_dispatch:
      
jobs:
  create_tag:
    name: create_tag
    uses: atulec016/central_call/.github/workflows/test.yml@main
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

